
server:
  port: 9191

spring:
  datasource:
    username: root
    password: root
    url: jdbc:mysql:///xdb
  mvc:
    servlet:
      load-on-startup: 0

  redis:
    port: 6379
    host: localhostS

  swagger:
    production: false
    enabled: true
logging:
  level:
    com.lantu: debug



mybatis-plus:
  global-config:
    db-config:
      logic-delete-field: deleted
      logic-not-delete-value: 0
      logic-delete-value: 1
  type-aliases-package: com.sz.*.entity
